server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: customer
          uri: http://localhost:8082
          predicates:
            - Path=/customers/**, 
        - id: rate
          uri: http://localhost:8083
          predicates:
            - Path=/raters/**, 
        - id: billing
          uri: http://localhost:8084
          predicates:
            - Path=/billings/**, 
        - id: settlement
          uri: http://localhost:8085
          predicates:
            - Path=/settlements/**, 
        - id: BoundedContext990
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/**, 
        - id: rate
          uri: http://rate:8080
          predicates:
            - Path=/raters/**, 
        - id: billing
          uri: http://billing:8080
          predicates:
            - Path=/billings/**, 
        - id: settlement
          uri: http://settlement:8080
          predicates:
            - Path=/settlements/**, 
        - id: BoundedContext990
          uri: http://boundedContext990:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
