apiVersion: apps/v1
kind: Deployment
metadata:
  name: my page
  labels:
    app: my page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my page
  template:
    metadata:
      labels:
        app: my page
    spec:
      containers:
        - name: my page
          image: "username/my page:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
